### ISSUE TITLE
Discard NetBeans project folder from repo

### ISSUE THREAD

**Issue by chesio** [Arsenal21/all-in-one-wordpress-security#40]
Hello AIOWPSF team,

While thinking about workflow that would help me avoid [commiting bugs](https://wordpress.org/support/topic/scanner-filesdirectories-to-ignore?replies=5) in the future, I came across [this cool plugin](https://github.com/afragen/github-updater) that allows to simply update any GitHub hosted WordPress plugin in your WordPress install.

Would you please consider turning this repo into a true plugin repo? That is to discard NetBeans project folder and place contents of `all-in-one-wp-security` folder in root folder of the repo?

With the AIOWPSF repo being a true plugin repo, I could use GitHub Updater plugin to run a branch from my fork on some of my websites and see if changes/fixes included in that branch are working as expected.

Greetings,
Česlav

**Comment by Arsenal21** [comment]
Hi Ceslav, internally we use netbeans editor and the projects are setup so it works with both the mercurial and github. This is not something we want to change since multiple developer work on this project (and everything is already setup nicely). You should be doing your development and uploading the files to your localhost setup (which is instant). If you use a localhost setup, you don't really need to use that other plugin (you an upload the full plugin in a couple of clicks and almost instantly). Most of the features can be tested on a localhost setup.

**Comment by chesio** [comment]
Hi, I develop on localhost, but we're a small company, so we have only one environment locally. AIOWPSF is a complex plugin and may perform quite differently in different environments. I started digging and patching the plugin when I noticed that it didn't work in production the same way it did on localhost. Now I have some patches developed for specific webhosts, but would like to test them in more environments to be sure they don't break something else at some other webhost and the Github Updater plugin seems to be the right tool for distribution of such patches.

I use NetBeans for development as well, but I don't think Netbeans project metadata needs to be versioned in repository this way. Anyway, I understand if you don't want to make the change. It would make it easier for me, that's why I asked. Thanks for the quick response!
